### ISSUE TITLE
QR codes not scanning

### ISSUE THREAD

**Issue by markclowes** [codemasher/php-qrcode#3]
QR codes generated with the same parameters in v.1.0.3 and up do not seem to scan correctly. Using v.1.0.2 the code scans perfectly. This is using examples/image.php.

**Comment by codemasher** [comment]
Hey, thanks for your report. I've changed a lot of loops and the structure in order to increase perfomance, might have missed something though. I'll look into it ASAP. (note to self: learn to write proper tests.)
