### ISSUE TITLE
QR breaks on long strings

### ISSUE THREAD

**Issue by als1979** [codemasher/php-qrcode#4]
Great project!

However it seems the generator fails on long strings like this:

eyJjdCI6IjVPSExXNzZQZUg1NitEUUdtcFwvY2FBPT0iLCJpdiI6ImY0ZTI4MGMyYjc2NDExZmJjMmUzMjc5NzA0MTc3YmI4IiwicyI6ImZjZTZlMTY3YjNjMTQwMDUifQ%3D%3D

![index](https://cloud.githubusercontent.com/assets/23328553/21139563/726a5d8a-c16e-11e6-899d-f3375cdc85b8.png)

**Comment by codemasher** [comment]
Thank you for your report! I'm going to look into it.

**Comment by codemasher** [comment]
Update: the bug has been introduced with this commit: https://github.com/codemasher/php-qrcode/commit/99084fcb9f2a30e17895bded65177334b3605857

Going to fix ASAP.

**Comment by codemasher** [comment]
So it *should* be fixed now and i'd be happy about feedback! Thanks!
