### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by gj12** [codemasher/php-qrcode#6]
`require_once '../vendor/autoload.php';`

The file `../vendor/autoload.php` is missing.

**Comment by codemasher** [comment]
step 1: [get composer](https://getcomposer.org/)
step 2: `composer install`
step 3: ???
step 4: profit!

**Comment by gj12** [comment]
Not everyone is using this stupid composer. It's like giving Microsoft "batch" a package manager. I'm now using another PHP QR lib which works without composer and you need only one include to use it!

**Comment by codemasher** [comment]
Number of fucks given: 0.

https://github.com/codemasher/php-qrcode#manual-installation

**Comment by gj12** [comment]
Importance of your little library: 0

**Comment by codemasher** [comment]
Obviously it's important enough for people (or bots) to troll about issues that don't exist.

RTFM or GTFO.
